FROM debian:testing

WORKDIR /src/kos

RUN apt-get -y update && apt-get --fix-missing -y install \
    apt-utils \
    g++ \
    git \
    make \
    texinfo \
    wget \
    bzip2

COPY compile-toolchain.sh /
ENTRYPOINT ["/compile-toolchain.sh"]
