FROM dc-toolchain:latest

ADD dc-toolchain.tar.gz /
ADD environ.sh /usr/local/dc/
ADD Makefile.kos /usr/local/dc/



RUN apt-get -y update && apt-get --fix-missing -y install \
    curl \
    python \    
    subversion \
    libjpeg-dev \
    libpng-dev \
    libelf-dev

COPY compile-kos.sh /
ENTRYPOINT ["/compile-kos.sh"]