all:
	make -C /src/kos all kos-ports_all
	make -C /src/tools/dcload-serial all install

install:
	mkdir /usr/local/dc/kos/kos
	mkdir /usr/local/dc/kos/kos-ports
	cp -r /src/kos/lib/ /usr/local/dc/kos/kos/
  cp -r /src/kos/include/ /usr/local/dc/kos/kos/
	cp -r /src/kos/addons /usr/local/dc/kos/kos/
	cp -r /src/kos-ports/lib /usr/local/dc/kos/kos-ports
  