FROM dc-toolchain:latest

ADD build-resources/dc-toolchain.tar.gz /
ADD build-resources/environ.sh /usr/local/dc/



RUN apt-get -y update && apt-get --fix-missing -y install \
    curl \
    python \    
    subversion \
    libjpeg-dev \
    libpng-dev