#!/bin/sh

PWD=`pwd`
#-v $PWD/kos-ports:/src/kos-ports
docker run -v $PWD/kos:/src/kos -it dc-toolchain:latest /bin/bash
docker run -v $PWD/tools:/src/tools -v $PWD/kos:/src/kos -v $PWD/kos-ports:/src/kos-ports -it dc-kos:latest /bin/bash
