FROM dc-toolchain:latest

RUN apt-get -y update && apt-get --fix-missing -y install \
    curl \
    python \    
    subversion \
    libjpeg-dev \
    libpng-dev \
    libelf-dev

ADD dc-toolchain.tar.gz /
ADD environ.sh /usr/local/dc/
ADD Makefile.kos /usr/local/dc/

COPY compile-kos.sh /
ENTRYPOINT ["/bin/sh", "/compile-kos.sh"]