FROM debian:testing

RUN apt-get -y update && apt-get --fix-missing -y install \
    curl \
    python \
    make \
    git \
    subversion \
    libogg-dev \
    libjpeg-dev \
    libpng-dev \
    libelf-dev

ENV DC_TOOLS /src/dc

ADD output/dc-toolchain.tar.gz /
ADD environ.sh /usr/local/dc/
ADD Makefile.kos /usr/local/dc/

COPY compile-kos.sh /
ENTRYPOINT ["/bin/sh", "/compile-kos.sh"]
