all:
	make -C /src/dc/kos all kos-ports_all
	make -C /src/dc/dcload-serial all install
	make -C /src/dc/dcload-ip all install
	mv /opt/toolchains/dc/bin/dc-tool /opt/toolchains/dc/bin/dc-tool-serial
	mv /usr/local/bin/dc-tool /opt/toolchains/dc/bin/dc-tool-ip

