FROM debian:10
LABEL maintainer="muller.john@gmail.com"
ARG BUILD_DATE
LABEL org.label-schema.build-date=$BUILD_DATE

WORKDIR /src/kos

RUN apt-get -y update && apt-get --fix-missing -y install \
    apt-utils \
    g++ \
    git \
    make \
    texinfo \
    wget \
    bzip2 \
    xz-utils

COPY compile-toolchain.sh /
ENTRYPOINT ["/bin/sh", "/compile-toolchain.sh"]
